title: Jessica Kersey # your name (or website title) here
logo: "images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am pursuing a MS in Business Analytics at Eccles School of Business, University of Utah. 
  <br><br>
  This portfolio includes notebooks for data analytic and machine learning projects I have completed. 
  <br><br>
  <a href="https://www.linkedin.com/in/jessica-a-dejong/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/j-kersey-24">Github</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: # your Google Analytics tracking ID here
